// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springsource.roo.loanrequest.server.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import org.springsource.roo.loanrequest.server.domain.LoanRequest;
import org.springsource.roo.loanrequest.server.domain.LoanRequestDataOnDemand;

privileged aspect LoanRequestDataOnDemand_Roo_DataOnDemand {
    
    declare @type: LoanRequestDataOnDemand: @Component;
    
    private Random LoanRequestDataOnDemand.rnd = new SecureRandom();
    
    private List<LoanRequest> LoanRequestDataOnDemand.data;
    
    public LoanRequest LoanRequestDataOnDemand.getNewTransientLoanRequest(int index) {
        LoanRequest obj = new LoanRequest();
        setAmount(obj, index);
        setCustomerName(obj, index);
        setProcessId(obj, index);
        return obj;
    }
    
    public void LoanRequestDataOnDemand.setAmount(LoanRequest obj, int index) {
        Double amount = new Integer(index).doubleValue();
        obj.setAmount(amount);
    }
    
    public void LoanRequestDataOnDemand.setCustomerName(LoanRequest obj, int index) {
        String customerName = "customerName_" + index;
        obj.setCustomerName(customerName);
    }
    
    public void LoanRequestDataOnDemand.setProcessId(LoanRequest obj, int index) {
        String processId = "processId_" + index;
        obj.setProcessId(processId);
    }
    
    public LoanRequest LoanRequestDataOnDemand.getSpecificLoanRequest(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        LoanRequest obj = data.get(index);
        Long id = obj.getId();
        return LoanRequest.findLoanRequest(id);
    }
    
    public LoanRequest LoanRequestDataOnDemand.getRandomLoanRequest() {
        init();
        LoanRequest obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return LoanRequest.findLoanRequest(id);
    }
    
    public boolean LoanRequestDataOnDemand.modifyLoanRequest(LoanRequest obj) {
        return false;
    }
    
    public void LoanRequestDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = LoanRequest.findLoanRequestEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'LoanRequest' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<LoanRequest>();
        for (int i = 0; i < 10; i++) {
            LoanRequest obj = getNewTransientLoanRequest(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
