// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springsource.roo.loanrequest.server.domain;

import org.springframework.beans.factory.annotation.Configurable;
import org.springsource.roo.loanrequest.server.domain.LoanRequestDataOnDemand;

privileged aspect LoanRequestDataOnDemand_Roo_Configurable {
    
    declare @type: LoanRequestDataOnDemand: @Configurable;
    
}
